bar
title File Size Distribution
x-axis ["train_resume.py", "train.py", "Encoder.tsx", "StegaStampModel", "Decoder.tsx", "imageProcessing", "bch.ts", "App.tsx", "useStegaStamp.t", "package.json"]
y-axis "Lines of Code" 0 --> 280
bar [280, 255, 157, 133, 118, 109, 104, 67, 36, 34]
