stateDiagram-v2
[*] --> Project
Project --> Functions: 24 total
Project --> Classes: 3 total
JSON --> Imports: 0
JSON --> Exports: 0
TSX --> Imports: 33
TSX --> Exports: 4
TypeScript --> Imports: 18
TypeScript --> Exports: 16
[*] --> [*]
